/*
 * generated by Xtext 2.21.0
 */
package workflow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WfDslUiModule extends AbstractWfDslUiModule {

	public WfDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
