/*
 * generated by Xtext 2.21.0
 */
package workflow;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WfDslStandaloneSetup extends WfDslStandaloneSetupGenerated {

	public static void doSetup() {
		new WfDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
